sonar.organization=20206205tech
sonar.projectKey=20206205Tech_code-payment-service

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sources=src
sonar.tests=test

sonar.exclusions=**/*.spec.ts, **/*.e2e-spec.ts
